### ISSUE TITLE
'AdversarialModel' object has no attribute '_feed_output_shapes'

### ISSUE THREAD

**Issue by HassamSheikh** [bstriner/keras-adversarial#12]
Any idea about this? I do not think this is a Keras 2 issue.

**Comment by bstriner** [comment]
It is a Keras-2 rename. Fixed in master now. This is the block that makes it work in keras-2.

```python
self._feed_loss_fns = self.loss_functions
self._feed_inputs = self.inputs
self._feed_input_names = self.input_names
self._feed_input_shapes = self.internal_input_shapes
self._feed_outputs = self.outputs
self._feed_output_names = self.output_names
self._feed_output_shapes = self.internal_output_shapes
self._feed_sample_weights = self.sample_weights
self._feed_sample_weight_modes = self.sample_weight_modes
```

Cheers

**Comment by shirishr** [comment]
@bstriner, this maybe a newbie question but I installed keras-adeversarial using:

python setup.py install --force

later when I run 

python example_gan_cifar10.py

I get an error:

File "example_gan_cifar10.py", line 18, in <module>
    from keras_adversarial.legacy import Dense, BatchNormalization, fit, l1l2, Convolution2D, AveragePooling2D
ImportError: No module named 'keras_adversarial.legacy'

Why? What did I do wrong?

**Comment by tanujay** [comment]
,,,,
