### ISSUE TITLE
example_gan.py TypeError

### ISSUE THREAD

**Issue by MaevaLC** [bstriner/keras-adversarial#27]
Hello,

Sorry to bother, I'm fairly new to Keras and everything. I'm trying to set up two adversarial neural networks, and your lib seems very interesting to me. I cloned the repository and installation went successfully. But I tried to launch example_gan.py, and I got an error. I don't understand enough yet to be able to solve it by myself...

I'm using Spyder 2.3.9, with Python 3.5, TensorFlow : 1.1.0, Keras : 2.0.4

The error is : "TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64"

PasteBin of the full Traceback : https://pastebin.com/0BaAcuQa

Any kind of help is appreciated :) !

**Comment by bstriner** [comment]
Issue with python 3. division is an int in python 2 but float in python 3. `Dense(hidden_dim/2)` should be `Dense(int(hidden_dim/2))`. Just add an `int` cast to the line that is failing.

See PR https://github.com/bstriner/keras-adversarial/pull/23

`example_gan` is fixed but the other examples probably have the same problem.

Cheers

**Comment by MaevaLC** [comment]
Thank you very much for fixing this !
I'm sorry to have not seen the PR related...

A tiny thing I changed myself, you might want to know about this :
line 110 : example_gan(AdversarialOptimizerSimultaneous(), "output/gan"),
I just changed "output/gan" to os.path.join("output", "gan"), since on Windows it was a problem.
I know it's not really important, I just wanted to help.

Anyway, thank you for all this work !
