### ISSUE TITLE
'Model' object has no attribute 'constraints'

### ISSUE THREAD

**Issue by muleejmx** [bstriner/keras-adversarial#36]
Hey, I was working through this tutorial: https://www.analyticsvidhya.com/blog/2017/06/introductory-generative-adversarial-networks-gans/. 

I'm trying to implement a simple GAN with the following code:
gan = simple_gan(model_1, model_2, normal_latent_sampling((100,)))

model = AdversarialModel(base_model=gan,
                         player_params=[model_1.trainable_weights, model_2.trainable_weights])

model.adversarial_compile(adversarial_optimizer=AdversarialOptimizerSimultaneous(),
                          player_optimizers=['adam', 'adam'],
                          loss='binary_crossentropy')

history = model.fit(x=train,
                    y=gan_targets(train.shape[0]),
                    epochs=10,
                    batch_size=batch_size)

However, I get this error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-5de57f2d803f> in <module>()
     11                     y=gan_targets(train.shape[0]),
     12                     epochs=10,
---> 13                     batch_size=batch_size)

/anaconda/envs/py27/lib/python2.7/site-packages/keras/engine/training.pyc in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1573         else:
   1574             ins = x + y + sample_weights
-> 1575         self._make_train_function()
   1576         f = self.train_function
   1577 

/anaconda/envs/py27/lib/python2.7/site-packages/keras_adversarial-0.0.3-py2.7.egg/keras_adversarial/adversarial_model.pyc in _make_train_function(self)
    159                                                                                  self.optimizers,
    160                                                                                  [model.constraints for model in
--> 161                                                                                   self.layers],
    162                                                                                  self.updates,
    163                                                                                  self._function_kwargs)

AttributeError: 'Model' object has no attribute 'constraints'

I'm thinking it might be an incompatibility between versions? I've tried a number of different tutorials and I always get this error while trying to call fit.

I've tried switching between Python 2 and 3; both use Tensorflow 1.3.0 and keras 2.0.8.

If I could get any help on what is causing this error it would be great :)

**Comment by d4nst** [comment]
The way constraints are managed has changed in Keras 2.0.8. The relevant commit is here: https://github.com/fchollet/keras/commit/2382f788b4f14646fa8b6b2d8d65f1fc138b35c4 To avoid this problem you should use a Keras version earlier than 2.0.8.

**Comment by d4nst** [comment]
I just submitted a PR to fix this issue: https://github.com/bstriner/keras-adversarial/pull/37

**Comment by bstriner** [comment]
@d4nst @muleejmx fix is in. Looks like everything works on both keras-1 and current keras-2

https://travis-ci.org/bstriner/keras-adversarial
