### ISSUE TITLE
Tensorflow issue

### ISSUE THREAD

**Issue by frojasaracena** [bstriner/keras-adversarial#41]
Hi, I tried to run the AAE example but got an error when calling `fit`:

`TypeError: run() got an unexpected keyword argument 'compile_kwargs'`

I appreciate your help.

Felipe

**Comment by cs2103t** [comment]
Someone changed adversarial_model.py and changed the name of the argument for model.compile. All you need to do is to revert back to older version of adversarial_model.py. It took me so long to understand this was the cause of the error. The error messages from keras and tensorflow just dont help sometimes.

**Comment by bstriner** [comment]
@frojasaracena @cs2103t sorry didn't update the examples earlier after that change to the backend. Fix  to aae examples is in master now. You can see the line below.

https://github.com/bstriner/keras-adversarial/commit/36f90f2e7f506a09da457b5c9d22d3073ae43339

Cheers
